import type { StationPreset } from '../types'

/** JAXA, ISRO, CNSA, and Korean sites. */
export const ASIA_STATIONS: StationPreset[] = [
  {
    id: 'jaxa-usuda',
    name: { ko: '우스다 심우주국', en: 'Usuda Deep Space Center' },
    network: 'jaxa',
    country: 'JP',
    lat_deg: 36.1331,
    lon_deg: 138.362,
    alt_m: 0,
    min_elev_deg: 10,
    source: 'https://www.wikidata.org/wiki/Q7902244',
    retrieved: '2026-09-19',
  },
  {
    id: 'jaxa-masuda',
    name: { ko: '마스다', en: 'Masuda' },
    network: 'jaxa',
    country: 'JP',
    lat_deg: 30.5559,
    lon_deg: 131.0161,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q11429311',
    retrieved: '2026-09-19',
  },
  {
    id: 'jaxa-okinawa',
    name: { ko: '오키나와', en: 'Okinawa' },
    network: 'jaxa',
    country: 'JP',
    lat_deg: 26.5005,
    lon_deg: 127.9035,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q11552678',
    retrieved: '2026-09-19',
  },
  {
    id: 'jaxa-ogasawara',
    name: { ko: '오가사와라', en: 'Ogasawara' },
    network: 'jaxa',
    country: 'JP',
    lat_deg: 27.0791,
    lon_deg: 142.2158,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q11463405',
    retrieved: '2026-09-19',
  },
  {
    id: 'jaxa-hatoyama',
    name: { ko: '지구관측센터 (하토야마)', en: 'Earth Observation Center' },
    network: 'jaxa',
    country: 'JP',
    lat_deg: 36.0031,
    lon_deg: 139.3492,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q5327099',
    retrieved: '2026-09-19',
  },
  {
    id: 'isro-istrac',
    name: { ko: 'ISTRAC 벵갈루루', en: 'ISTRAC Bengaluru' },
    network: 'isro',
    country: 'IN',
    lat_deg: 13.036,
    lon_deg: 77.5111,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q6021612',
    retrieved: '2026-09-19',
  },
  {
    id: 'isro-byalalu',
    name: { ko: '인도 심우주망 (뱌랄루)', en: 'Indian Deep Space Network' },
    network: 'isro',
    country: 'IN',
    lat_deg: 12.9016,
    lon_deg: 77.3686,
    alt_m: 0,
    min_elev_deg: 10,
    source: 'https://www.wikidata.org/wiki/Q6020227',
    retrieved: '2026-09-19',
  },
  {
    id: 'isro-hassan',
    name: { ko: '하산 주관제소', en: 'Master Control Facility Hassan' },
    network: 'isro',
    country: 'IN',
    lat_deg: 13.0717,
    lon_deg: 76.0994,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q3520782',
    retrieved: '2026-09-19',
  },
  {
    id: 'isro-lucknow',
    name: { ko: '럭나우', en: 'Lucknow' },
    network: 'isro',
    country: 'IN',
    lat_deg: 26.9123,
    lon_deg: 80.9561,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q127294667',
    retrieved: '2026-09-19',
  },
  {
    id: 'cnsa-jiamusi',
    name: { ko: '자무쓰 심우주국', en: 'Jiamusi Deep Space Station' },
    network: 'cnsa',
    country: 'CN',
    lat_deg: 46.4936,
    lon_deg: 130.7711,
    alt_m: 0,
    min_elev_deg: 10,
    source: 'https://www.wikidata.org/wiki/Q141442726',
    retrieved: '2026-09-19',
  },
  {
    id: 'cnsa-espacio-lejano',
    name: { ko: '에스파시오 레하노', en: 'Espacio Lejano' },
    network: 'cnsa',
    country: 'AR',
    lat_deg: -38.1914,
    lon_deg: -70.1495,
    alt_m: 0,
    min_elev_deg: 10,
    source: 'https://www.wikidata.org/wiki/Q20014921',
    retrieved: '2026-09-19',
  },
  {
    id: 'kari-naro',
    name: { ko: '나로우주센터', en: 'Naro Space Center' },
    network: 'kari',
    country: 'KR',
    lat_deg: 34.4319,
    lon_deg: 127.5351,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q495281',
    retrieved: '2026-09-19',
  },
  {
    id: 'kari-daejeon',
    name: { ko: '한국항공우주연구원 본원 (대전)', en: 'KARI Headquarters (Daejeon)' },
    network: 'kari',
    country: 'KR',
    lat_deg: 36.3694,
    lon_deg: 127.364,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q494948',
    retrieved: '2026-09-19',
    note: {
      ko: '연구원 본원 전체 기준 좌표',
      en: 'Coordinate is for the institute campus as a whole.',
    },
  },
  {
    id: 'kari-jangbogo',
    name: { ko: '장보고 과학기지', en: 'Jang Bogo Station' },
    network: 'kopri',
    country: 'AQ',
    lat_deg: -74.6167,
    lon_deg: 164.2,
    alt_m: 36,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q245875',
    retrieved: '2026-09-19',
    note: {
      ko: '남극 기지 전체 기준 좌표',
      en: 'Coordinate is for the research station as a whole.',
    },
  },
  {
    id: 'kari-sejong',
    name: { ko: '세종 과학기지', en: 'King Sejong Station' },
    network: 'kopri',
    country: 'AQ',
    lat_deg: -62.2232,
    lon_deg: -58.7865,
    alt_m: 10,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q246364',
    retrieved: '2026-09-19',
    note: {
      ko: '남극 기지 전체 기준 좌표',
      en: 'Coordinate is for the research station as a whole.',
    },
  },
]
