import type { StationPreset } from '../types'

/** ESA ESTRACK stations, plus the INTA and SSC sites ESA operates from. */
export const ESA_STATIONS: StationPreset[] = [
  {
    id: 'estrack-cebreros',
    name: { ko: '세브레로스', en: 'Cebreros' },
    network: 'estrack',
    country: 'ES',
    lat_deg: 40.4528,
    lon_deg: -4.3676,
    alt_m: 794,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q2889659',
    retrieved: '2026-09-19',
  },
  {
    id: 'estrack-kiruna',
    name: { ko: '키루나', en: 'Kiruna' },
    network: 'estrack',
    country: 'SE',
    lat_deg: 67.8572,
    lon_deg: 20.9644,
    alt_m: 402,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q4349991',
    retrieved: '2026-09-19',
  },
  {
    id: 'estrack-kourou',
    name: { ko: '쿠루', en: 'Kourou' },
    network: 'estrack',
    country: 'GF',
    lat_deg: 5.2514,
    lon_deg: -52.8047,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q18126941',
    retrieved: '2026-09-19',
    note: {
      ko: '기록된 표고가 해수면보다 낮아 0 m로 둠',
      en: 'The recorded elevation is below sea level, so it is kept at 0 m.',
    },
  },
  {
    id: 'estrack-malargue',
    name: { ko: '말라르궤', en: 'Malargüe' },
    network: 'estrack',
    country: 'AR',
    lat_deg: -35.776,
    lon_deg: -69.3982,
    alt_m: 1550,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q6741341',
    retrieved: '2026-09-19',
  },
  {
    id: 'estrack-new-norcia',
    name: { ko: '뉴노르시아', en: 'New Norcia' },
    network: 'estrack',
    country: 'AU',
    lat_deg: -31.0482,
    lon_deg: 116.191,
    alt_m: 252,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q4302461',
    retrieved: '2026-09-19',
  },
  {
    id: 'estrack-redu',
    name: { ko: '레뒤', en: 'Redu' },
    network: 'estrack',
    country: 'BE',
    lat_deg: 50.0019,
    lon_deg: 5.1467,
    alt_m: 387,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q3497409',
    retrieved: '2026-09-19',
  },
  {
    id: 'estrack-santa-maria',
    name: { ko: '산타마리아', en: 'Santa Maria' },
    network: 'estrack',
    country: 'PT',
    lat_deg: 36.9972,
    lon_deg: -25.1357,
    alt_m: 276,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q18354889',
    retrieved: '2026-09-19',
  },
  {
    id: 'estrack-villafranca',
    name: { ko: '비야프랑카', en: 'Villafranca' },
    network: 'estrack',
    country: 'ES',
    lat_deg: 40.4426,
    lon_deg: -3.9516,
    alt_m: 665,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q18167242',
    retrieved: '2026-09-19',
  },
  {
    id: 'estrack-perth',
    name: { ko: '퍼스', en: 'Perth' },
    network: 'estrack',
    country: 'AU',
    lat_deg: -31.8025,
    lon_deg: 115.885,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q4303156',
    retrieved: '2026-09-19',
    note: { ko: 'ESA 운영 종료', en: 'ESA has since closed this station.' },
  },
  {
    id: 'inta-maspalomas',
    name: { ko: '마스팔로마스', en: 'Maspalomas' },
    network: 'inta',
    country: 'ES',
    lat_deg: 27.7634,
    lon_deg: -15.6335,
    alt_m: 205,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q4302441',
    retrieved: '2026-09-19',
  },
  {
    id: 'ssc-esrange',
    name: { ko: '에스레인지', en: 'Esrange' },
    network: 'ssc',
    country: 'SE',
    lat_deg: 67.8917,
    lon_deg: 21.0814,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q1368518',
    retrieved: '2026-09-19',
  },
]
