import type { StationPreset } from '../types'

/** NASA Deep Space Network complexes and Near Space Network sites. */
export const NASA_STATIONS: StationPreset[] = [
  {
    id: 'dsn-goldstone',
    name: { ko: '골드스톤 (DSN)', en: 'Goldstone (DSN)' },
    network: 'dsn',
    country: 'US',
    lat_deg: 35.42667,
    lon_deg: -116.89,
    alt_m: 899,
    min_elev_deg: 10,
    source: 'https://www.wikidata.org/wiki/Q618630',
    retrieved: '2026-09-25',
    note: {
      ko: '위키데이터 표고 2,950 ft를 미터로 환산한 값',
      en: 'Wikidata elevation of 2,950 ft converted to metres.',
    },
  },
  {
    id: 'dsn-madrid',
    name: { ko: '마드리드 (DSN)', en: 'Madrid (DSN)' },
    network: 'dsn',
    country: 'ES',
    lat_deg: 40.43139,
    lon_deg: -4.24806,
    alt_m: 0,
    min_elev_deg: 10,
    source: 'https://www.wikidata.org/wiki/Q618721',
    retrieved: '2026-09-19',
  },
  {
    id: 'dsn-canberra',
    name: { ko: '캔버라 (DSN)', en: 'Canberra (DSN)' },
    network: 'dsn',
    country: 'AU',
    lat_deg: -35.40139,
    lon_deg: 148.98167,
    alt_m: 0,
    min_elev_deg: 10,
    source: 'https://www.wikidata.org/wiki/Q1032865',
    retrieved: '2026-09-19',
  },
  {
    id: 'nsn-wallops',
    name: { ko: '월롭스', en: 'Wallops' },
    network: 'nsn',
    country: 'US',
    lat_deg: 37.93333,
    lon_deg: -75.46778,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://en.wikipedia.org/wiki/Wallops_Flight_Facility',
    retrieved: '2026-09-19',
    note: {
      ko: '비행시설 전체 기준 좌표',
      en: 'Coordinate is for the flight facility, not a single antenna.',
    },
  },
  {
    id: 'nsn-white-sands',
    name: { ko: '화이트샌즈', en: 'White Sands' },
    network: 'nsn',
    country: 'US',
    lat_deg: 32.507,
    lon_deg: -106.611,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q618540',
    retrieved: '2026-09-19',
  },
  {
    id: 'nsn-mcmurdo',
    name: { ko: '맥머도', en: 'McMurdo' },
    network: 'nsn',
    country: 'AQ',
    lat_deg: -77.84632,
    lon_deg: 166.66824,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://en.wikipedia.org/wiki/McMurdo_Station',
    retrieved: '2026-09-19',
    note: {
      ko: '기지 전체 기준 좌표',
      en: 'Coordinate is for the research station, not the antenna.',
    },
  },
]
