import type { StationPreset } from '../types'

/** CNES, CONAE, and SANSA stations. */
export const OTHER_STATIONS: StationPreset[] = [
  {
    id: 'cnes-aussaguel',
    name: { ko: '이쉬스오사게 (툴루즈)', en: 'Issus-Aussaguel' },
    network: 'cnes',
    country: 'FR',
    lat_deg: 43.4289,
    lon_deg: 1.4978,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q3155726',
    retrieved: '2026-09-19',
  },
  {
    id: 'cnes-galliot',
    name: { ko: '갈리오 (쿠루)', en: 'Galliot (Kourou)' },
    network: 'cnes',
    country: 'GF',
    lat_deg: 5.0986,
    lon_deg: -52.6397,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q35993927',
    retrieved: '2026-09-19',
  },
  {
    id: 'conae-cordoba',
    name: { ko: '코르도바', en: 'Córdoba' },
    network: 'conae',
    country: 'AR',
    lat_deg: -31.5238,
    lon_deg: -64.464,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q5845110',
    retrieved: '2026-09-19',
  },
  {
    id: 'conae-tierra-del-fuego',
    name: { ko: '티에라델푸에고', en: 'Tierra del Fuego' },
    network: 'conae',
    country: 'AR',
    lat_deg: -54.5103,
    lon_deg: -67.115,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q42373251',
    retrieved: '2026-09-19',
  },
  {
    id: 'sansa-hartebeesthoek',
    name: { ko: '하르테비스훅', en: 'Hartebeesthoek' },
    network: 'sansa',
    country: 'ZA',
    lat_deg: -25.8875,
    lon_deg: 27.7084,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q114684888',
    retrieved: '2026-09-19',
  },
]
