import type { StationPreset } from '../types'

/** KSAT polar sites and the other commercial networks that share them. */
export const POLAR_STATIONS: StationPreset[] = [
  {
    id: 'ksat-svalbard',
    name: { ko: '스발바르 (SvalSat)', en: 'Svalbard (SvalSat)' },
    network: 'ksat',
    country: 'NO',
    lat_deg: 78.2298,
    lon_deg: 15.4078,
    alt_m: 450,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q1796135',
    retrieved: '2026-09-19',
    note: {
      ko: '플라토베리에트 고원 400~500 m 중간값을 표고로 사용',
      en: 'Elevation is the middle of the 400-500 m Plataberget plateau.',
    },
  },
  {
    id: 'ksat-troll',
    name: { ko: '트롤 (TrollSat)', en: 'Troll (TrollSat)' },
    network: 'ksat',
    country: 'AQ',
    lat_deg: -72.0167,
    lon_deg: 2.5333,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q7845173',
    retrieved: '2026-09-19',
  },
  {
    id: 'ksat-tromso',
    name: { ko: '트롬쇠', en: 'Tromsø' },
    network: 'ksat',
    country: 'NO',
    lat_deg: 69.6618,
    lon_deg: 18.9417,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q7845399',
    retrieved: '2026-09-19',
  },
  {
    id: 'ksat-inuvik',
    name: { ko: '이누빅', en: 'Inuvik' },
    network: 'ksat',
    country: 'CA',
    lat_deg: 68.3175,
    lon_deg: -133.5339,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q1671644',
    retrieved: '2026-09-19',
  },
  {
    id: 'ksat-nyalesund',
    name: { ko: '니올레순 (콩스피오르)', en: 'Ny-Ålesund (Kongsfjord)' },
    network: 'ksat',
    country: 'NO',
    lat_deg: 78.93,
    lon_deg: 11.855,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q6429241',
    retrieved: '2026-09-19',
  },
  {
    id: 'sonz-awarua',
    name: { ko: '아와루아', en: 'Awarua' },
    network: 'sonz',
    country: 'NZ',
    lat_deg: -46.5129,
    lon_deg: 168.376,
    alt_m: 0,
    min_elev_deg: 5,
    source: 'https://www.wikidata.org/wiki/Q4829919',
    retrieved: '2026-09-19',
  },
]
